### ISSUE TITLE
API 

### ISSUE THREAD

**Issue by JGieseWeb** [JGieseWeb/tankApp#10]
#### Description

Implement the API to the project

#### Tasks

Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.

- [x] Find a good API 
- [x] Implement the API into the Project  
- [x] Implement the Information in the Pages
