### ISSUE TITLE
Filter Card

### ISSUE THREAD

**Issue by JGieseWeb** [JGieseWeb/tankApp#14]
#### Description

Create the Filter card that navigate to the Alle or Favoriten Page

#### Screenshots

![image](https://user-images.githubusercontent.com/82370428/121505653-4c4ff600-c9e3-11eb-9c23-db171d74bb68.png)

#### Tasks

Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.

- [x] Create the Filter card  
- [x] create the Alle button
- [x] create the pop out checkboxes
