### ISSUE TITLE
Suchmethode

### ISSUE THREAD

**Issue by JGieseWeb** [JGieseWeb/tankApp#15]
#### Description

Suchmethode is to choose between "Aktueller Standort" or "Umkreissuche" with an input field
where to search  

#### Screenshots

![image](https://user-images.githubusercontent.com/82370428/121506845-676f3580-c9e4-11eb-84b9-6e094ccc83ab.png)

#### Tasks

Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.

- [x] Create the Suchmethode card
- [x] create the Aktueller Standort button
- [x] create the pop out  card with the options
