### ISSUE TITLE
Suchradius

### ISSUE THREAD

**Issue by JGieseWeb** [JGieseWeb/tankApp#16]
#### Description

the Suchradius field is to Specify in which radius to search

#### Screenshots

![image](https://user-images.githubusercontent.com/82370428/121507698-2af00980-c9e5-11eb-9dc6-a377076dbaf1.png)

#### Tasks

Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.

- [x] Create the Suchradius card 
- [x] Implement the XXKm Button 
- [x] create the pop out card with an input field
