### ISSUE TITLE
Spritsorte

### ISSUE THREAD

**Issue by JGieseWeb** [JGieseWeb/tankApp#17]
#### Description

This option is to specify which fuel  you need and filters 

#### Screenshots

![image](https://user-images.githubusercontent.com/82370428/121508252-b073b980-c9e5-11eb-870f-1b420d2427a0.png)

#### Tasks

Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.

- [ ] create the Spritsorte card 
- [ ] Implement the Sort Button 
- [ ] Create the pop out options
