### ISSUE TITLE
Anzahl Ergebnisse

### ISSUE THREAD

**Issue by JGieseWeb** [JGieseWeb/tankApp#18]
#### Description
The Anzahl Ergebnisse card is to specify how much Tanstelleninfocards shown on the pages

#### Screenshots

![image](https://user-images.githubusercontent.com/82370428/121509665-2d536300-c9e7-11eb-8824-0d2f39e7348c.png)

#### Tasks

Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.

- [x] create the Anzahl Ergebnisse card 
- [x] Implement the max. Button 
- [x] Create the pop out options
